<script setup lang="ts">
import WorkspacePanel from '@/components/WorkspacePanel.vue'
import { computed, reactive, ref } from 'vue'
import { Plus } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { createCreditCard, createLoan } from '@/api/finance'
import { money, ratio, sumMoney, today } from '@/finance/utils/money'
import type { CreditCard, Loan, RepaymentMethod } from '@/types/finance'
import FinanceIcon from './FinanceIcon.vue'

const props = defineProps<{ cards: CreditCard[]; loans: Loan[] }>()
const emit = defineEmits<{ changed: [] }>()
const cardVisible = ref(false)
const loanVisible = ref(false)
const saving = ref(false)
const cardDraft = reactive({ name: '', institution: '', maskedAccountNumber: '', creditLimit: '', currentDebt: '', statementAmount: '', minimumPayment: '0.00', billingDay: 1, repaymentDay: 1, nextPaymentDate: '', hasInstallment: false, notes: '' })
const loanDraft = reactive({ name: '', loanType: 'consumer', principal: '', remainingPrincipal: '', annualInterestRate: '', termMonths: 12, repaymentMethod: 'annuity' as RepaymentMethod, startDate: today(), endDate: '', monthlyPayment: '', nextPaymentDate: '', lender: '', notes: '' })
const totalLimit = computed(() => sumMoney(props.cards.map(item => item.creditLimit)))
const totalDebt = computed(() => sumMoney(props.cards.map(item => item.currentDebt)))
const statement = computed(() => sumMoney(props.cards.map(item => item.statementAmount)))
const loanRemaining = computed(() => sumMoney(props.loans.map(item => item.remainingPrincipal)))
const loanTypes: Record<string, string> = { consumer: '消费贷', credit: '信用贷', car: '车贷', personal: '个人借款', other: '其他贷款' }
function cardStatus(item: CreditCard) { if (!item.nextPaymentDate) return { key: 'normal', label: '正常' }; const days = Math.ceil((new Date(`${item.nextPaymentDate}T00:00:00`).getTime() - new Date(`${today()}T00:00:00`).getTime()) / 86400000); return days < 0 ? { key: 'overdue', label: '已逾期' } : days === 0 ? { key: 'today', label: '今日到期' } : days <= 7 ? { key: 'soon', label: '临近还款' } : { key: 'normal', label: '正常' } }
function openCard() { Object.assign(cardDraft, { name: '', institution: '', maskedAccountNumber: '', creditLimit: '', currentDebt: '', statementAmount: '', minimumPayment: '0.00', billingDay: 1, repaymentDay: 1, nextPaymentDate: '', hasInstallment: false, notes: '' }); cardVisible.value = true }
function openLoan() { Object.assign(loanDraft, { name: '', loanType: 'consumer', principal: '', remainingPrincipal: '', annualInterestRate: '', termMonths: 12, repaymentMethod: 'annuity', startDate: today(), endDate: '', monthlyPayment: '', nextPaymentDate: '', lender: '', notes: '' }); loanVisible.value = true }
async function saveCard() { if (!cardDraft.name || !cardDraft.creditLimit) { ElMessage.warning('请填写信用卡名称和额度'); return }; saving.value = true; try { await createCreditCard(cardDraft); ElMessage.success('信用卡已添加'); cardVisible.value = false; emit('changed') } finally { saving.value = false } }
async function saveLoan() { if (!loanDraft.name || !loanDraft.principal || !loanDraft.remainingPrincipal || !loanDraft.monthlyPayment) { ElMessage.warning('请填写贷款核心信息'); return }; saving.value = true; try { await createLoan(loanDraft); ElMessage.success('贷款已添加'); loanVisible.value = false; emit('changed') } finally { saving.value = false } }
defineExpose({ openCard, openLoan })
</script>

<template>
  <div class="finance-tab-stack">
    <section><div class="finance-section-heading"><div><p>信用卡</p><h2>额度与账单</h2></div><el-button :icon="Plus" @click="openCard">添加信用卡</el-button></div>
      <div class="finance-stat-grid debt-stat-grid"><article class="finance-metric"><span>总信用额度</span><strong>{{ money(totalLimit) }}</strong></article><article class="finance-metric"><span>总已用额度</span><strong>{{ money(totalDebt) }}</strong></article><article class="finance-metric"><span>整体利用率</span><strong>{{ ratio(totalDebt, totalLimit).toFixed(1) }}%</strong></article><article class="finance-metric"><span>本期待还</span><strong>{{ money(statement) }}</strong></article></div>
      <div v-if="cards.length" class="debt-card-grid"><article v-for="item in cards" :key="item.id" class="credit-card"><header><FinanceIcon kind="credit-card" :institution="item.institution" :size="38" /><div><strong>{{ item.name }}</strong><small>{{ item.institution }} {{ item.maskedAccountNumber }}</small></div><em :class="cardStatus(item).key">{{ cardStatus(item).label }}</em></header><div class="credit-main"><span>本期账单</span><b>{{ money(item.statementAmount) }}</b></div><div class="credit-details"><span>信用额度<b>{{ money(item.creditLimit) }}</b></span><span>已用额度<b>{{ money(item.currentDebt) }}</b></span><span>还款日<b>{{ item.nextPaymentDate || `每月 ${item.repaymentDay} 日` }}</b></span></div><div class="finance-progress"><i :style="{ width: `${Math.min(100, ratio(item.currentDebt, item.creditLimit))}%` }" :class="{ risk: ratio(item.currentDebt, item.creditLimit) >= 70 }" /></div><footer><span>额度利用率</span><b>{{ ratio(item.currentDebt, item.creditLimit).toFixed(1) }}%</b></footer></article></div>
      <div v-else class="finance-panel finance-empty compact"><FinanceIcon kind="credit-card" :size="42" /><strong>暂无信用卡</strong><span>添加信用卡后可跟踪额度利用率、账单和还款日。</span></div>
    </section>
    <section><div class="finance-section-heading"><div><p>一般借贷</p><h2>贷款管理</h2></div><el-button :icon="Plus" @click="openLoan">添加贷款</el-button></div><div class="loan-summary"><span>剩余贷款本金</span><strong>{{ money(loanRemaining) }}</strong></div>
      <div v-if="loans.length" class="loan-list"><article v-for="item in loans" :key="item.id"><FinanceIcon class="loan-icon" kind="loan" :size="34" /><div><strong>{{ item.name }}</strong><small>{{ loanTypes[item.loanType] || item.loanType }} · {{ item.lender || '未填写机构' }}</small></div><span><small>剩余本金</small><b>{{ money(item.remainingPrincipal) }}</b></span><span><small>年利率</small><b>{{ item.annualInterestRate }}%</b></span><span><small>月供</small><b>{{ money(item.monthlyPayment) }}</b></span><span><small>下次还款</small><b>{{ item.nextPaymentDate || '--' }}</b></span></article></div>
      <div v-else class="finance-panel finance-empty compact"><FinanceIcon kind="loan" :size="42" /><strong>暂无一般贷款</strong><span>消费贷、信用贷、车贷和个人借款可统一管理。</span></div>
    </section>

    <WorkspacePanel v-model="cardVisible" title="添加信用卡"><el-form label-position="top"><div class="finance-form-grid"><el-form-item label="卡片名称" required><el-input v-model="cardDraft.name" placeholder="如：招商银行 VISA" /></el-form-item><el-form-item label="发卡行"><el-input v-model="cardDraft.institution" /></el-form-item><el-form-item label="卡号尾号"><el-input v-model="cardDraft.maskedAccountNumber" placeholder="只填写尾号即可" /></el-form-item><el-form-item label="信用额度" required><el-input v-model="cardDraft.creditLimit"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="当前已用额度"><el-input v-model="cardDraft.currentDebt"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="本期账单"><el-input v-model="cardDraft.statementAmount"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="最低还款额"><el-input v-model="cardDraft.minimumPayment"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="下一还款日"><el-date-picker v-model="cardDraft.nextPaymentDate" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="账单日"><el-input-number v-model="cardDraft.billingDay" :min="1" :max="31" /></el-form-item><el-form-item label="还款日"><el-input-number v-model="cardDraft.repaymentDay" :min="1" :max="31" /></el-form-item></div><el-checkbox v-model="cardDraft.hasInstallment">本期包含分期</el-checkbox><el-form-item label="备注"><el-input v-model="cardDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="cardVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveCard">保存</el-button></template></WorkspacePanel>
    <WorkspacePanel v-model="loanVisible" title="添加一般贷款"><el-form label-position="top"><div class="finance-form-grid"><el-form-item label="贷款名称" required><el-input v-model="loanDraft.name" /></el-form-item><el-form-item label="类型"><el-select v-model="loanDraft.loanType"><el-option v-for="(label, value) in loanTypes" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="贷款本金" required><el-input v-model="loanDraft.principal"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="剩余本金" required><el-input v-model="loanDraft.remainingPrincipal"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="年利率（%）"><el-input v-model="loanDraft.annualInterestRate" /></el-form-item><el-form-item label="期限（月）"><el-input-number v-model="loanDraft.termMonths" :min="1" :max="600" /></el-form-item><el-form-item label="还款方式"><el-select v-model="loanDraft.repaymentMethod"><el-option label="等额本息" value="annuity" /><el-option label="等额本金" value="equal_principal" /></el-select></el-form-item><el-form-item label="月供" required><el-input v-model="loanDraft.monthlyPayment"><template #prepend>￥</template></el-input></el-form-item><el-form-item label="开始日期"><el-date-picker v-model="loanDraft.startDate" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="下一还款日"><el-date-picker v-model="loanDraft.nextPaymentDate" value-format="YYYY-MM-DD" type="date" /></el-form-item><el-form-item label="贷款机构"><el-input v-model="loanDraft.lender" /></el-form-item><el-form-item label="结束日期"><el-date-picker v-model="loanDraft.endDate" value-format="YYYY-MM-DD" type="date" /></el-form-item></div><el-form-item label="备注"><el-input v-model="loanDraft.notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="loanVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="saveLoan">保存</el-button></template></WorkspacePanel>
  </div>
</template>
